// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDysDxYwY61y3Yf6U6YmEpQaDJJX5o7uc0',
    appId: '1:475528068861:web:e34a4bd5b1deab7a4dc894',
    messagingSenderId: '475528068861',
    projectId: 'personadd-c023e',
    authDomain: 'personadd-c023e.firebaseapp.com',
    storageBucket: 'personadd-c023e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUjWKHvrQppXRc3pvIxS4K47tTlS3KIV8',
    appId: '1:475528068861:android:7558c4a97aeb92594dc894',
    messagingSenderId: '475528068861',
    projectId: 'personadd-c023e',
    storageBucket: 'personadd-c023e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABRvsST2_J2wX7vscrGzRJP9ur28o48Io',
    appId: '1:475528068861:ios:5a0bce175eb3d0da4dc894',
    messagingSenderId: '475528068861',
    projectId: 'personadd-c023e',
    storageBucket: 'personadd-c023e.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABRvsST2_J2wX7vscrGzRJP9ur28o48Io',
    appId: '1:475528068861:ios:31377a6f557eed524dc894',
    messagingSenderId: '475528068861',
    projectId: 'personadd-c023e',
    storageBucket: 'personadd-c023e.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
